/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package package1;

/**
 *
 * @author hari ji
 */
public class accessories extends javax.swing.JFrame {

    /**
     * Creates new form accessories
     */
    public accessories() 
    {
        initComponents();
    }
    
    public accessories(String carName, long carprice)
    {
        initComponents();
        carpri = carprice;
        jLabel1.setText("Accessories of " + carName);
        bcarname=carName;
    }

  
  

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chkantenna = new javax.swing.JCheckBox();
        chkxenonlight = new javax.swing.JCheckBox();
        chktrunk = new javax.swing.JCheckBox();
        chkgps = new javax.swing.JCheckBox();
        chkpower = new javax.swing.JCheckBox();
        chksunroof = new javax.swing.JCheckBox();
        chkgear = new javax.swing.JCheckBox();
        chkheater = new javax.swing.JCheckBox();
        chktouch = new javax.swing.JCheckBox();
        chkparking = new javax.swing.JCheckBox();
        chkmoonroof = new javax.swing.JCheckBox();
        chkbrake = new javax.swing.JCheckBox();
        chkbumper = new javax.swing.JCheckBox();
        chkboost = new javax.swing.JCheckBox();
        chkstigers = new javax.swing.JCheckBox();
        totalbill = new javax.swing.JButton();
        txtaccessories = new javax.swing.JTextField();
        accessoriesbill = new javax.swing.JButton();
        txtaccessoriesamount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 255, 255));
        jLabel1.setText("ACCESSORIES ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 16, 444, 37));

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        chkantenna.setText("Antenna");

        chkxenonlight.setText("Xenon Light");

        chktrunk.setText("Trunk Light");

        chkgps.setText("GPS Navigation");

        chkpower.setText("Power Window");

        chksunroof.setText("Sun Roof");

        chkgear.setText("Gear Shift Indicator");

        chkheater.setText("Heater");

        chktouch.setText("Touch Screen Display");

        chkparking.setText("Parking Sensor ");

        chkmoonroof.setText("Moon Roof");
        chkmoonroof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkmoonroofActionPerformed(evt);
            }
        });

        chkbrake.setText("Brake Assist");

        chkbumper.setText("Bumper Accessories");

        chkboost.setText("Boost");

        chkstigers.setText("Stigers");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkantenna)
                    .addComponent(chkxenonlight)
                    .addComponent(chktrunk)
                    .addComponent(chkpower)
                    .addComponent(chkgps))
                .addGap(133, 133, 133)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(chksunroof)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chkmoonroof))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chktouch)
                                    .addComponent(chkparking))
                                .addGap(111, 111, 111)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chkstigers)
                                    .addComponent(chkboost))
                                .addGap(0, 18, Short.MAX_VALUE)))
                        .addGap(96, 96, 96))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkgear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkbrake)
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(chkheater)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chkbumper)
                        .addGap(52, 52, 52))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkantenna)
                    .addComponent(chksunroof)
                    .addComponent(chkmoonroof))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkxenonlight)
                    .addComponent(chkgear)
                    .addComponent(chkbrake))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chktrunk)
                    .addComponent(chkheater)
                    .addComponent(chkbumper))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkboost)
                    .addComponent(chktouch)
                    .addComponent(chkpower))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkgps)
                    .addComponent(chkparking)
                    .addComponent(chkstigers))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 59, -1, -1));

        totalbill.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        totalbill.setForeground(new java.awt.Color(0, 204, 204));
        totalbill.setText("Total Bill");
        totalbill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalbillMouseClicked(evt);
            }
        });
        totalbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalbillActionPerformed(evt);
            }
        });
        getContentPane().add(totalbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 230, 34));

        txtaccessories.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        getContentPane().add(txtaccessories, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 457, 166, 30));

        accessoriesbill.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        accessoriesbill.setForeground(new java.awt.Color(0, 204, 204));
        accessoriesbill.setText("Accessories Bill");
        accessoriesbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accessoriesbillActionPerformed(evt);
            }
        });
        getContentPane().add(accessoriesbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 390, 230, 34));

        txtaccessoriesamount.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        txtaccessoriesamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaccessoriesamountActionPerformed(evt);
            }
        });
        getContentPane().add(txtaccessoriesamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 457, 168, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText(" No Of Accessories :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 230, 20));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(309, 463, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setText("Amount of Accessories :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 250, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/accessories.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 510));

        setSize(new java.awt.Dimension(837, 559));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int countingacc,accamount;
long carpri;String bcarname;
    private void chkmoonroofActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkmoonroofActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkmoonroofActionPerformed

    private void totalbillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalbillMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_totalbillMouseClicked

    private void totalbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalbillActionPerformed
        // TODO add your handling code here:
        new netbill(countingacc,accamount,carpri).show();
        this.dispose();
       
    }//GEN-LAST:event_totalbillActionPerformed

    private void accessoriesbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accessoriesbillActionPerformed
        // TODO add your handling code here:
        int counting=0;
       int totalamount=0;
        if(chkantenna.isSelected())
        {
          counting=countComponents();
          totalamount=40000;
          
        }
        if(chkboost.isSelected())
        {
           counting=counting+countComponents();
       totalamount=totalamount+60000;
           
        }
         if(chkbrake.isSelected())
        {
           
        counting=counting+countComponents();
        totalamount=totalamount+70000;
        
        }
          if(chkbumper.isSelected())
        {
           
       counting=counting+countComponents();
       totalamount=totalamount+60000;
       
        }
           if(chkgear.isSelected())
        {
       counting=counting+countComponents();
       totalamount=totalamount+65000;
       
        }
            if(chkgps.isSelected())
        {
       counting=counting+countComponents();
       totalamount=totalamount+65000;
       
        }
             if(chkheater.isSelected())
        {
       counting=counting+countComponents();
       totalamount=totalamount+80000;
       
        }
              if(chkmoonroof.isSelected())
        {
       counting=counting+countComponents();
       totalamount=totalamount+90000;
       
        }
               if(chkparking.isSelected())
        {
       counting=counting+countComponents();
       totalamount=totalamount+85000;
       
        }
                if(chkpower.isSelected())
        {
       counting=counting+countComponents();
       totalamount=totalamount+80000;
       
        }
                 if(chkstigers.isSelected())
        {
       counting=counting+countComponents();
       
       totalamount=totalamount+60000;
        }
                  if(chksunroof.isSelected())
        {
       counting=counting+countComponents();
       totalamount=totalamount+90000;
       
        }
                   if(chktouch.isSelected())
        {
       counting=counting+countComponents();
       totalamount=totalamount+100000;
        }
                    if(chktrunk.isSelected())
        {
       counting=counting+countComponents();
       totalamount=totalamount+70000;
        }
                     if(chkxenonlight.isSelected())
        {
       counting=+counting+countComponents(); 
       
       totalamount=totalamount+120000;
        }
                     
        txtaccessories.setText(counting+"");
        txtaccessoriesamount.setText(totalamount+"");
        countingacc = counting;
        accamount=totalamount;
    }//GEN-LAST:event_accessoriesbillActionPerformed

    private void txtaccessoriesamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaccessoriesamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaccessoriesamountActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(accessories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(accessories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(accessories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accessories.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new accessories().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton accessoriesbill;
    private javax.swing.JCheckBox chkantenna;
    private javax.swing.JCheckBox chkboost;
    private javax.swing.JCheckBox chkbrake;
    private javax.swing.JCheckBox chkbumper;
    private javax.swing.JCheckBox chkgear;
    private javax.swing.JCheckBox chkgps;
    private javax.swing.JCheckBox chkheater;
    private javax.swing.JCheckBox chkmoonroof;
    private javax.swing.JCheckBox chkparking;
    private javax.swing.JCheckBox chkpower;
    private javax.swing.JCheckBox chkstigers;
    private javax.swing.JCheckBox chksunroof;
    private javax.swing.JCheckBox chktouch;
    private javax.swing.JCheckBox chktrunk;
    private javax.swing.JCheckBox chkxenonlight;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton totalbill;
    private javax.swing.JTextField txtaccessories;
    private javax.swing.JTextField txtaccessoriesamount;
    // End of variables declaration//GEN-END:variables
}
