/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package package1;
import com.sun.corba.se.impl.orbutil.ObjectUtility;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author hari ji
 */
public class customerentry extends javax.swing.JFrame {

    /**
     * Creates new form customerentry
     */
    public customerentry()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtfirstname = new javax.swing.JTextField();
        txtlastname = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        registerb = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        txtcarorder = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        clearB = new javax.swing.JButton();
        ExitB = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtpermantaddress = new javax.swing.JTextField();
        txtmobileno = new javax.swing.JTextField();
        dateofregistor = new com.toedter.calendar.JDateChooser();
        dateofdeliver = new com.toedter.calendar.JDateChooser();
        dateofbirth = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Lucida Bright", 2, 36)); // NOI18N
        jLabel13.setText("REGISTRATION ");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Customer Name :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        txtfirstname.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel1.add(txtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 170, 30));

        txtlastname.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel1.add(txtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, 160, 30));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel14.setText("Date of Registration :");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, -1, -1));

        registerb.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        registerb.setText("Register");
        registerb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbMouseClicked(evt);
            }
        });
        registerb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerbActionPerformed(evt);
            }
        });
        jPanel1.add(registerb, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 140, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("(First Name)");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel6.setText("(Last Name) ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jRadioButton2.setText("Male");
        jPanel1.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jRadioButton1.setText("Female");
        jPanel1.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, -1, -1));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setText("Gender :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        txtcarorder.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtcarorder.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BMW", "Audi", "Mercedes" }));
        txtcarorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcarorderActionPerformed(evt);
            }
        });
        jPanel1.add(txtcarorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 190, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel12.setText("Selected Car:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, -1, -1));

        clearB.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        clearB.setText("Clear");
        clearB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBActionPerformed(evt);
            }
        });
        jPanel1.add(clearB, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 480, 120, -1));

        ExitB.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        ExitB.setText("Exit");
        ExitB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBActionPerformed(evt);
            }
        });
        jPanel1.add(ExitB, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 480, 110, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel15.setText("Date of Deliver :");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel8.setText("Date of Birth :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel16.setText(" Permant Address : ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        txtpermantaddress.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel1.add(txtpermantaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 230, 30));

        txtmobileno.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        txtmobileno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtmobilenoKeyTyped(evt);
            }
        });
        jPanel1.add(txtmobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 230, 30));

        dateofregistor.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel1.add(dateofregistor, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 190, 30));

        dateofdeliver.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel1.add(dateofdeliver, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 230, 190, 30));

        dateofbirth.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel1.add(dateofbirth, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 230, 30));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel17.setText("Mobile No :");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel18.setText("Email ID:");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        txtemail.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jPanel1.add(txtemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 230, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/customerentryimage.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(865, 577));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_registerbMouseClicked

    private void registerbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerbActionPerformed
        // TODO add your handling code here:
        try {
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/carshowroom","root","root");
            Statement stmt=con.createStatement();

            String customername,firstname,lastname;
            firstname=txtfirstname.getText();
            lastname=txtlastname.getText();
            customername= firstname + " " + lastname;
       
            String dateStr=dateofregistor.getDate().toString();
            SimpleDateFormat formatter = new SimpleDateFormat("E MMM dd HH:mm:ss Z yyyy");
            Date date = (Date)formatter.parse(dateStr);  

            Calendar cal = Calendar.getInstance();
            cal.setTime(date);
            String regdate =  cal.get(Calendar.YEAR) +  "/" + (cal.get(Calendar.MONTH) + 1) + "/" + cal.get(Calendar.DATE) ;

            String peraddres=txtpermantaddress.getText();
            String mobileno=txtmobileno.getText();
            
            String carselected=txtcarorder.getSelectedItem().toString();

            String  qry="Insert into registration values('"+customername+"','"+peraddres+"','"+mobileno+"','"+carselected+"','"+regdate+"')";
            stmt.executeUpdate(qry);
       
               if(txtcarorder.getSelectedIndex()==0)
        {
            new bmwdetails().show();
            dispose();
        }
        if(txtcarorder.getSelectedIndex()==1)
        {
            new audidetails().show();
            dispose();
        }
        if(txtcarorder.getSelectedIndex()==2)
        {
            new mercedesdetails().show();
            dispose();
        }

        }
        catch(SQLException | ParseException ex)
        {
            JOptionPane.showMessageDialog(this, ex);
        }
            
         
       
    }//GEN-LAST:event_registerbActionPerformed

    private void txtcarorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcarorderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcarorderActionPerformed

    private void clearBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBActionPerformed
        // TODO add your handling code here:
        txtfirstname.setText("");
        txtlastname.setText("");
        txtemail.setText("");
        txtmobileno.setText("");
        txtpermantaddress.setText("");
        buttonGroup1.clearSelection();
        dateofbirth.setDate(new Date());
        dateofdeliver.setDate(new Date());
        dateofregistor.setDate(new Date());
        txtcarorder.setSelectedIndex(0);
    }//GEN-LAST:event_clearBActionPerformed

    private void ExitBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitBActionPerformed

    private void txtmobilenoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtmobilenoKeyTyped
        // TODO add your handling code here:
        char ch=evt.getKeyChar();
        if(!(ch>='0'&&ch<='9'))
        {
             evt.consume();
        
       
        }
    }//GEN-LAST:event_txtmobilenoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerentry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExitB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton clearB;
    private com.toedter.calendar.JDateChooser dateofbirth;
    private com.toedter.calendar.JDateChooser dateofdeliver;
    private com.toedter.calendar.JDateChooser dateofregistor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JButton registerb;
    private javax.swing.JComboBox txtcarorder;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtfirstname;
    private javax.swing.JTextField txtlastname;
    private javax.swing.JTextField txtmobileno;
    private javax.swing.JTextField txtpermantaddress;
    // End of variables declaration//GEN-END:variables
}
