/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package package1;
  import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
/**
 *
 * @author hari ji
 */
public class netbill extends javax.swing.JFrame {

    /**
     * Creates new form netbill
     */
    public netbill() {
        initComponents();
    }
 public netbill(int countingacc, int accamount, long carprice)
    {
    initComponents();
    //txtnoaccessories.setText(countingacc+"");
   //txtpriceacc.setText(accamount+"");
    //txtcarprice.setText(carprice + ""); 
    noaccessories=countingacc;
    priceacc=accamount;
    Acarprice=carprice;
            }

       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtmobileno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtcustname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtpermantadd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtregistration = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcarselected = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtcarprice = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnoaccessories = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtpriceacc = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txttotalprice = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        calculatebill = new javax.swing.JButton();
        gotohome = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Mobile No : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 225, 138, -1));

        txtmobileno.setEditable(false);
        txtmobileno.setFont(new java.awt.Font("Brush Script MT", 2, 18)); // NOI18N
        getContentPane().add(txtmobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 228, 202, 31));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Customer Name :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 109, -1, -1));

        txtcustname.setFont(new java.awt.Font("Brush Script MT", 2, 18)); // NOI18N
        getContentPane().add(txtcustname, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 109, 202, 31));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Permant Address :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 308, -1, -1));

        txtpermantadd.setEditable(false);
        txtpermantadd.setFont(new java.awt.Font("Brush Script MT", 2, 18)); // NOI18N
        getContentPane().add(txtpermantadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 311, 202, 31));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("Registration Date : ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 395, -1, -1));

        txtregistration.setEditable(false);
        txtregistration.setFont(new java.awt.Font("Brush Script MT", 2, 18)); // NOI18N
        getContentPane().add(txtregistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(245, 395, 202, 31));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setText(" Car Selected :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 114, 165, -1));

        txtcarselected.setEditable(false);
        txtcarselected.setFont(new java.awt.Font("Brush Script MT", 2, 18)); // NOI18N
        getContentPane().add(txtcarselected, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 114, 184, 31));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Car Price :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(513, 225, 110, -1));

        txtcarprice.setEditable(false);
        txtcarprice.setFont(new java.awt.Font("Brush Script MT", 2, 18)); // NOI18N
        getContentPane().add(txtcarprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(746, 225, 184, 34));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 0, 0));
        jLabel7.setText("Total No. Of Accessories : ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        txtnoaccessories.setEditable(false);
        txtnoaccessories.setFont(new java.awt.Font("Brush Script MT", 2, 18)); // NOI18N
        getContentPane().add(txtnoaccessories, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 310, 184, 34));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 0, 0));
        jLabel8.setText("Total Price Of Accessories :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, -1, -1));

        txtpriceacc.setEditable(false);
        txtpriceacc.setFont(new java.awt.Font("Brush Script MT", 2, 18)); // NOI18N
        getContentPane().add(txtpriceacc, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, 196, 31));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("Total Price : ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 511, 183, 25));

        txttotalprice.setEditable(false);
        txttotalprice.setFont(new java.awt.Font("Brush Script MT", 2, 18)); // NOI18N
        getContentPane().add(txttotalprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 503, 221, 33));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Signature Of Showroom Owner");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 520, 250, 60));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/signatureowner.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 460, 160, 70));

        jLabel12.setFont(new java.awt.Font("Lucida Bright", 3, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("BILL PAYMENT");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 399, -1));

        calculatebill.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        calculatebill.setForeground(new java.awt.Color(0, 0, 51));
        calculatebill.setText("Calculate Bill");
        calculatebill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatebillActionPerformed(evt);
            }
        });
        getContentPane().add(calculatebill, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 543, -1, 33));

        gotohome.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        gotohome.setForeground(new java.awt.Color(0, 0, 51));
        gotohome.setText("Go To Registration");
        gotohome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gotohomeActionPerformed(evt);
            }
        });
        getContentPane().add(gotohome, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 540, 230, 33));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/billimage1.jpg"))); // NOI18N
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 590));

        setSize(new java.awt.Dimension(1009, 634));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int counting,noaccessories,priceacc;
long Acarprice,cp,tp,accprice;

    private void calculatebillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatebillActionPerformed
        // TODO add your handling code here:
        String mobileno;String regdate;
       String customername,carselected;String peraddres;
       customername=txtcustname.getText();
     try
     {
         Class.forName("com.mysql.jdbc.Driver");
             Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/carshowroom","root","root");
             Statement stmt=con.createStatement();
             String qry="select * from registration where customername='"+customername+"'";
                     
             ResultSet rs=stmt.executeQuery(qry);
             if(rs.next())
             {
            
             peraddres=rs.getString(2);
             mobileno=rs.getString(3);
             carselected=rs.getString(4);
              regdate=rs.getDate(5).toString();
              
             txtregistration.setText(regdate + "");
             txtpermantadd.setText(peraddres+"");
             txtmobileno.setText(mobileno+"");
             txtcarselected.setText(carselected);
             
             txtnoaccessories.setText(noaccessories+"");
   txtpriceacc.setText(priceacc+"");
    txtcarprice.setText(Acarprice + ""); 
     tp=priceacc+Acarprice;
     txttotalprice.setText(tp+"");
               int totalcarprice;
    totalcarprice=Integer.parseInt(txtcarprice.getText());
             }
             else
             {
                 JOptionPane.showMessageDialog(this, "No Record Found");
             }
                     
     }
     catch(Exception ex)
     {
     JOptionPane.showMessageDialog(this,"Error in Finding Record");
     }
    
     
    }//GEN-LAST:event_calculatebillActionPerformed

    private void gotohomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gotohomeActionPerformed
        // TODO add your handling code here:
        new customerentry().show();
        this.dispose();
    }//GEN-LAST:event_gotohomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(netbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(netbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(netbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(netbill.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new netbill().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton calculatebill;
    private javax.swing.JButton gotohome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtcarprice;
    private javax.swing.JTextField txtcarselected;
    private javax.swing.JTextField txtcustname;
    private javax.swing.JTextField txtmobileno;
    private javax.swing.JTextField txtnoaccessories;
    private javax.swing.JTextField txtpermantadd;
    private javax.swing.JTextField txtpriceacc;
    private javax.swing.JTextField txtregistration;
    private javax.swing.JTextField txttotalprice;
    // End of variables declaration//GEN-END:variables
}
